"""ht_tva_optionnels_et_mouvements_bancaires

Revision ID: 1cd6f5a62909
Revises: 21b970ad6d7e
Create Date: 2026-07-25 19:51:32.378980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd6f5a62909'
down_revision: Union[str, Sequence[str], None] = '21b970ad6d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecritures_comptables', 'montant_ht',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('ecritures_comptables', 'taux_tva',
               existing_type=postgresql.ENUM('TAUX_20', 'TAUX_14', 'TAUX_10', 'TAUX_7', 'TAUX_0', name='taux_tva_enum'),
               nullable=True)
    op.alter_column('ecritures_comptables', 'montant_tva',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecritures_comptables', 'montant_tva',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('ecritures_comptables', 'taux_tva',
               existing_type=postgresql.ENUM('TAUX_20', 'TAUX_14', 'TAUX_10', 'TAUX_7', 'TAUX_0', name='taux_tva_enum'),
               nullable=False)
    op.alter_column('ecritures_comptables', 'montant_ht',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###
