"""ajout table taches (Rappels et Taches)

Revision ID: 21b970ad6d7e
Revises: e8fd7f46f06e
Create Date: 2026-07-25 02:22:15.545905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b970ad6d7e'
down_revision: Union[str, Sequence[str], None] = 'e8fd7f46f06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
