"""create_taches_table

Revision ID: 65a34d21d0e5
Revises: 1cd6f5a62909
Create Date: 2026-07-26 20:42:53.815441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a34d21d0e5'
down_revision: Union[str, Sequence[str], None] = '1cd6f5a62909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taches',
    sa.Column('entreprise_id', sa.UUID(), nullable=True),
    sa.Column('cree_par', sa.UUID(), nullable=False),
    sa.Column('assignee_a', sa.UUID(), nullable=True),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('A_FAIRE', 'EN_COURS', 'TERMINEE', name='statut_tache_enum'), nullable=False),
    sa.Column('priorite', sa.Enum('BASSE', 'NORMALE', 'HAUTE', name='priorite_tache_enum'), nullable=False),
    sa.Column('recurrence', sa.Enum('AUCUNE', 'MENSUELLE', 'TRIMESTRIELLE', 'ANNUELLE', name='recurrence_tache_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cree_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taches_cabinet_id'), 'taches', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_taches_date_echeance'), 'taches', ['date_echeance'], unique=False)
    op.create_index(op.f('ix_taches_entreprise_id'), 'taches', ['entreprise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taches_entreprise_id'), table_name='taches')
    op.drop_index(op.f('ix_taches_date_echeance'), table_name='taches')
    op.drop_index(op.f('ix_taches_cabinet_id'), table_name='taches')
    op.drop_table('taches')
    # ### end Alembic commands ###
