"""initial tables

Revision ID: ba0aefae0e94
Revises: 
Create Date: 2026-07-08 22:18:45.225185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba0aefae0e94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('ice', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ice')
    )
    op.create_table('entreprises',
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('ice', sa.String(length=20), nullable=True),
    sa.Column('identifiant_fiscal', sa.String(length=20), nullable=True),
    sa.Column('rc', sa.String(length=20), nullable=True),
    sa.Column('forme_juridique', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creee_automatiquement', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cabinet_id', 'ice', name='uq_entreprise_cabinet_ice')
    )
    op.create_index(op.f('ix_entreprises_cabinet_id'), 'entreprises', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_entreprises_ice'), 'entreprises', ['ice'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN_CABINET', 'EXPERT_COMPTABLE', 'CHEF_MISSION', 'COLLABORATEUR', 'ASSISTANT', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cabinet_id'), 'users', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_cabinet_id'), 'audit_logs', ['cabinet_id'], unique=False)
    op.create_table('chronos',
    sa.Column('entreprise_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', name='uq_chrono_entreprise')
    )
    op.create_index(op.f('ix_chronos_cabinet_id'), 'chronos', ['cabinet_id'], unique=False)
    op.create_table('documents',
    sa.Column('entreprise_id', sa.UUID(), nullable=False),
    sa.Column('chrono_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.Enum('CLIENTS', 'FOURNISSEURS', 'BANQUE', 'CNSS', 'TVA', 'IMPOTS', 'ACHATS', 'VENTES', 'DIVERS', name='categorie_document_enum'), nullable=False),
    sa.Column('nom_fichier_original', sa.String(length=500), nullable=False),
    sa.Column('chemin_stockage', sa.String(length=1000), nullable=False),
    sa.Column('hash_fichier', sa.String(length=64), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'EN_TRAITEMENT', 'TRAITE', 'VALIDE', 'ERREUR', name='statut_document_enum'), nullable=False),
    sa.Column('texte_ocr', sa.Text(), nullable=True),
    sa.Column('donnees_extraites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_erreur', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chrono_id'], ['chronos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_arbo', 'documents', ['entreprise_id', 'annee', 'mois', 'categorie'], unique=False)
    op.create_index(op.f('ix_documents_cabinet_id'), 'documents', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_documents_hash_fichier'), 'documents', ['hash_fichier'], unique=False)
    op.create_table('ecritures_comptables',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('entreprise_id', sa.UUID(), nullable=False),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('type_ecriture', sa.Enum('ACHAT', 'VENTE', 'BANQUE', 'CNSS', 'IMPOT', 'AUTRE', name='type_ecriture_enum'), nullable=False),
    sa.Column('numero_piece', sa.String(length=100), nullable=True),
    sa.Column('date_piece', sa.Date(), nullable=True),
    sa.Column('tiers', sa.String(length=255), nullable=True),
    sa.Column('montant_ht', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Enum('TAUX_20', 'TAUX_14', 'TAUX_10', 'TAUX_7', 'TAUX_0', name='taux_tva_enum'), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut_validation', sa.Enum('BROUILLON', 'A_VERIFIER', 'VALIDE', 'REJETE', name='statut_validation_enum'), nullable=False),
    sa.Column('anomalie_detectee', sa.Boolean(), nullable=False),
    sa.Column('anomalie_details', sa.Text(), nullable=True),
    sa.Column('doublon_potentiel_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doublon_potentiel_id'], ['ecritures_comptables.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_comptables_cabinet_id'), 'ecritures_comptables', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_document_id'), 'ecritures_comptables', ['document_id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_entreprise_id'), 'ecritures_comptables', ['entreprise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecritures_comptables_entreprise_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_document_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_cabinet_id'), table_name='ecritures_comptables')
    op.drop_table('ecritures_comptables')
    op.drop_index(op.f('ix_documents_hash_fichier'), table_name='documents')
    op.drop_index(op.f('ix_documents_cabinet_id'), table_name='documents')
    op.drop_index('ix_documents_arbo', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chronos_cabinet_id'), table_name='chronos')
    op.drop_table('chronos')
    op.drop_index(op.f('ix_audit_logs_cabinet_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cabinet_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_entreprises_ice'), table_name='entreprises')
    op.drop_index(op.f('ix_entreprises_cabinet_id'), table_name='entreprises')
    op.drop_table('entreprises')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
