"""make document classification fields nullable

Revision ID: f29924d2e6e1
Revises: ba0aefae0e94
Create Date: 2026-07-09 02:57:21.838373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f29924d2e6e1'
down_revision: Union[str, Sequence[str], None] = 'ba0aefae0e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'entreprise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'chrono_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'annee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'mois',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'categorie',
               existing_type=postgresql.ENUM('CLIENTS', 'FOURNISSEURS', 'BANQUE', 'CNSS', 'TVA', 'IMPOTS', 'ACHATS', 'VENTES', 'DIVERS', name='categorie_document_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'categorie',
               existing_type=postgresql.ENUM('CLIENTS', 'FOURNISSEURS', 'BANQUE', 'CNSS', 'TVA', 'IMPOTS', 'ACHATS', 'VENTES', 'DIVERS', name='categorie_document_enum'),
               nullable=False)
    op.alter_column('documents', 'mois',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'annee',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'chrono_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('documents', 'entreprise_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
